# ==========================================
#        CIDARIS CRAFT - Configuration
# ==========================================

database:
  type: "SQLITE" # MARIADB, MYSQL, POSTGRESQL, SQLITE, YAML, JSON
  host: "localhost"
  port: 3306
  database: "cidaris"
  username: "root"
  password: "password"

webhook:
  enabled: true
  url: "https://discord.com/api/webhooks/1474433559073657004/D5XzugZrX5NYgZdRU23NFmQg7wLqPWxD3kCNuDUyDt2qFfrfiA0FdGnxfjH4u6Aw8JF1"

wiki-heads:
  unlocked: "6105"      # Tête Verte (Débloqué)
  unlockable: "6101"    # Tête Jaune (Prêt à acheter)
  locked-parents: "6103" # Tête Rouge (Parent manquant)
  locked-resources: "8619" # Tête Orange (Ressources manquantes)
wiki_origin_item:
  material: QUARTZ_BLOCK
  name: " "
  lore: []
wiki_path_item:
  material: STICK
  name: " "
  glow: false
wiki_path_item_unlocked:
  material: BLAZE_ROD
  name: " "
  glow: true

blueprint:
  hdb: "41033"
  material: PAPER
  name: "&b&lBlueprint Mystère"
  lore:
    - "&7Rendez-vous dans le menu des Blueprints"
    - "&7pour fouiller cet objet et découvrir"
    - "&7le craft qu'il renferme."
    -
blueprint_revealed:
  hdb: "41032"
  material: EMPTY_MAP
  name: "&a&lPlan : &e%craft_name%"
  lore:
    - "&7Rareté : &f%rarity%"
    - ""
    - "&a► Clic-Droit pour débloquer"
    - "&a  sans payer de ressources !"

blueprint_rarities:
  commun: 60.0
  rare: 25.0
  epique: 10.0
  legendaire: 5.0